# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Roberts Kovalauskis
title: Test Automation Engineer / Technical Quality Assurer / SDET
email: robert.kovalauskis@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username: robertkovalauskis
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: roberts-kovalauskis-4266701a3
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#  - title: itsgoingto.be
#    icon: fas fa-globe
#    url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! I'm a Test Automation Engineer with 3 years of experience in Agile projects. During this time I mostly worked with <mark>Java</mark> and <mark>C#</mark> programming languages and developed test automation using frameworks like <mark>TestNG</mark> and <mark>NUnit</mark>.
  
  I have experience in developing a <mark>Selenium 4</mark> test automation framework from scratch and deploying <mark>Selenium Grid</mark> in <mark>AWS</mark> using <mark>Docker</mark> for running tests in the Cloud.
  
  I also have several certifications, including the <mark>ISTQB Foundation level</mark>, which gave me a structured overview of the role and <mark>best practices</mark> of testing in the <mark>Software Development Life Cycle</mark>.
  
  What I like the most about my job is that it requires me to constantly grow professionally and obtain new skills. I also like to communicate with my teammates to find solutions to the challenges we have.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Visma Labs
        link: www.visma.lv/visma-labs/
        # link_text: boringcompany.com
        sub_title: Technical Quality Assurer
        caption: November 2022 - Present
        quote: >
          Make progress happen
        description: | # this will include new lines to allow paragraphs
          Application for Recruitment specialists:
          - Develop <mark>test automation framework</mark> using <mark>C#</mark>, <mark>Selenium</mark>, <mark>NUnit</mark>;
          - Configure and deploy <mark>SeleniumGrid</mark> in <mark>AWS</mark>
          - Execute full <mark>regression testing</mark> of application;
          - Detect <mark>software defects</mark>, report them, and track further;
          - Write <mark>manual test cases</mark> and prepare product <mark>release reports</mark>;

      - layout: left
        title: Accenture Baltics
        link: www.accenture.com/lv-en/about/company/about-latvia
        # link_text: boringcompany.com
        sub_title: Quality Assurance Engineer
        caption: Aug 2020 - Nov 2022
        quote: >
          Accent on the future
        description: | # this will include new lines to allow paragraphs
          Banking Compliance project:
          - Develop <mark>test automation framework</mark> using <mark>Java</mark>, <mark>Selenium</mark>, <mark>TestNG</mark>;
          - Perform <mark>RESTful API test automation</mark>;
          - Execute full <mark>regression testing</mark> of application;
          - Analyze <mark>business requirements</mark> (specifications);
          - Detect <mark>software defects</mark>, report about them, and track further;
          - Write <mark>manual test cases</mark> and prepare product <mark>release reports</mark>;
          - <mark>Onboard</mark> and <mark>train new-joiners</mark> within the project;
          - Directly <mark>communicate with the Client</mark>.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Selenium WebDriver with Docker, Jenkins & AWS
        caption: Mar 2023 - Apr 2023
        sub_title: Udemy course
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          In this course I learned a lot about Docker and how to run tests in containers.

      - layout: left
        title: Java Programming Masterclass covering Java 11 & Java 17
        caption: Mar 2022 - Jul 2022
        sub_title: Udemy course
        #        quote: >
        #          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          In this course I learned a lot about Java.

      - layout: left
        title: University of Latvia
        caption: Feb 2021 - Jan 2022
        sub_title: Computer Science
        #        quote: >
        #          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Hack my career academic IT study program courses provided by the University of Latvia, Faculty of Computing, organized by Accenture.

      - layout: left
        title: QA.GURU Test Automation course
        caption: Nov 2020 - Mar 2021
        sub_title: Test automation engineer
        #        quote: >
        #          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Great course about Test automation using Java, Selenoid, Allure Reports.

      - layout: left
        title: Accenture Automation Testing Bootcamp
        caption: Aug 2020 - Aug 2020
        sub_title: Software tester intern
        #        quote: >
        #          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Accenture Bootcamp opened for me the doors into the world of IT. Since then I have never regretted the chosen path.

      - layout: left
        title: Software Development Academy
        caption: 2020 - 2020
        sub_title: Software tester
        #        quote: >
        #          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          This course was an introduction into the profession of Software Tester. Theoretical materials allowed me to obtain an ISTQB Foundational level certification.

  - title: Licenses & certifications
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CCNA Introduction to Networks
        caption: Issued Jan 2022
        sub_title: Cisco
        #        quote: >
        #          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs

      - layout: left
        title: Microsoft Certified Azure Fundamentals
        caption: Issued Jul 2021
        sub_title: Microsoft
        #        quote: >
        #          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs

      - layout: left
        title: edX Verified Certificate for HTML5 and CSS Fundamentals
        caption:
          Issued May 2021
          Credential ID 0066f3a77d8c4b618d4c598ffe43cf13
        sub_title: edX
        #        quote: >
        #          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        link: https://courses.edx.org/certificates/0066f3a77d8c4b618d4c598ffe43cf13
        link_text: Certificate
        description: | # this will include new lines to allow paragraphs

      - layout: left
        title: ISTQB Certified Tester, Foundational Level
        caption:
          Issued Aug 2020
          Credential ID 20-CTFL-177156-12
        sub_title: ISTQB - International Software Testing Qualifications Board
        #        quote: >
        #          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        link: http://scr.istqb.org/
        link_text: Certificate
        description: | # this will include new lines to allow paragraphs

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Reading non-fiction
      - Gaming
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
